global:
    api-listen-addr: :5183
    timeout: 10s
    memo: chelsea smile#8177
    light-cache-size: 20
chains:
    gaia:
        type: cosmos
        value:
            key: wallet
            chain-id: GAIA
            rpc-addr: http://95.217.210.247:23657
            account-prefix: cosmos
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 0.001uatom
            debug: true
            timeout: 10s
            output-format: json
            sign-mode: sync
            strategy:
            type: native
            version: ics20-1
            order: UNORDERED 
    stride:
        type: cosmos
        value:
            key: wallet
            chain-id: STRIDE-TESTNET-2
            rpc-addr: http://95.216.191.183:16657
            account-prefix: stride
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 0.001ustrd
            debug: true
            timeout: 10s
            output-format: json
            sign-mode: sync
            strategy:
            type: native
            version: ics20-1
            order: UNORDERED         
paths:
    gaia-stride:
        src:
            chain-id: GAIA
            client-id: 07-tendermint-0
            connection-id: connection-0
        dst:
            chain-id: STRIDE-TESTNET-2
            client-id: 07-tendermint-0
            connection-id: connection-0
        src-channel-filter:
            rule: allowlist
            channel-list:
                - channel-0
                - channel-1
                - channel-2
                - channel-3
                - channel-4
        dst-channel-filter:
            rule: allowlist
            channel-list:
                - channel-0 
                - channel-1 
                - channel-2 
                - channel-3 
                - channel-4
